apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: langfuse-credentials
  namespace: langfuse
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: langfuse-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: salt
      remoteRef:
        key: platform/langfuse
        property: salt
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: encryption_key
      remoteRef:
        key: platform/langfuse
        property: encryption_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: nextauth_secret
      remoteRef:
        key: platform/langfuse
        property: nextauth_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: postgres_password
      remoteRef:
        key: platform/langfuse
        property: postgres_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: redis_password
      remoteRef:
        key: platform/langfuse
        property: redis_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: clickhouse_password
      remoteRef:
        key: platform/langfuse
        property: clickhouse_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: minio_root_user
      remoteRef:
        key: platform/langfuse
        property: minio_root_user
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: minio_root_password
      remoteRef:
        key: platform/langfuse
        property: minio_root_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
