baseURL = "https://viper.maniak.ai/"
languageCode = "en-us"
title = "k8s-viper"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term", "RSS", "sitemap"]
relativeURLs = false
canonifyURLs = false

[params]
  description = "public light handbook for Viper SandboxAgents + lab map."
  github = "https://github.com/sebbycorp/k8s-viper"
  defaultNodeIP = "172.16.10.135"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

[outputs]
  home = ["HTML"]
  section = ["HTML"]
