# Dummy key only. Real OpenAI credentials stay on agentgateway
# (Vault secret/platform/openai → ExternalSecret openai-secret).
# Do not replace this with a live API key or license JWT.
apiVersion: v1
kind: Secret
metadata:
  name: kagent-openai
  namespace: kagent
  labels:
    app.kubernetes.io/name: kagent
    app.kubernetes.io/part-of: kagent
type: Opaque
stringData:
  OPENAI_API_KEY: sk-routed-via-agentgateway
