apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kagent
resources:
  - dummy-openai-secret.yaml
  - hello-substrate.yaml
  - ui-nodeport.yaml
  - fortigate-external-secret.yaml
  - fortigate-mcp.yaml
  - fortigate-agent.yaml
  - f5-bigip-external-secret.yaml
  - f5-bigip-mcp.yaml
  - f5-bigip-skills.yaml
  - f5-bigip-agent.yaml
  - arista-ceos-external-secret.yaml
  - arista-ceos-mcp.yaml
  - arista-ceos-skills.yaml
  - arista-ceos-agent.yaml
