apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: vault
    repo: https://helm.releases.hashicorp.com
    version: 0.30.0
    releaseName: vault
    namespace: vault
    valuesFile: values.yaml
patches:
  - path: sts-vct-defaults.yaml
    target:
      group: apps
      version: v1
      kind: StatefulSet
      name: vault
