apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agentgateway-system
resources:
  - namespace.yaml
  - external-secret-openai.yaml
  - gateway.yaml
  - backend-openai.yaml
  - httproute-openai.yaml
  - backend-dgx-spark.yaml
  - httproute-dgx-spark.yaml
  - backend-desktop.yaml
  - httproute-desktop.yaml
  - otel-collector.yaml
  - gateway-parameters-tracing.yaml
