apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: viper
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: k8s-viper single-node platform and applications
  sourceRepos:
    - https://github.com/sebbycorp/k8s-viper.git
    - https://helm.releases.hashicorp.com
    - https://charts.external-secrets.io
    - https://kubernetes-sigs.github.io/headlamp/
    - https://langfuse.github.io/langfuse-k8s
    - https://github.com/kubernetes-sigs/gateway-api
    - cr.agentgateway.dev/charts
    - oci://cr.agentgateway.dev/charts
    - oci://cr.agentgateway.dev/charts/agentgateway
    - oci://cr.agentgateway.dev/charts/agentgateway-crds
    - oci://cr.agentgateway.dev/*
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: vault
      server: https://kubernetes.default.svc
    - namespace: external-secrets
      server: https://kubernetes.default.svc
    - namespace: headlamp
      server: https://kubernetes.default.svc
    - namespace: apps
      server: https://kubernetes.default.svc
    - namespace: default
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
    - namespace: agentgateway-system
      server: https://kubernetes.default.svc
    - namespace: langfuse
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
