apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: viper
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault
      targetRevision: 0.30.0
      helm:
        releaseName: vault
        valueFiles:
          - $values/platform/vault/values.yaml
    - repoURL: https://github.com/sebbycorp/k8s-viper.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        - .spec.template.metadata.annotations."checksum/config"
        - .spec.template.metadata.annotations."vault.hashicorp.com/config-checksum"
        - .metadata.annotations."checksum/config"
        - .metadata.annotations."vault.hashicorp.com/config-checksum"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
