apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-agentgateway-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: viper
  source:
    repoURL: oci://cr.agentgateway.dev/charts/agentgateway-crds
    chart: agentgateway-crds
    targetRevision: v1.4.1
    helm:
      releaseName: agentgateway-crds
  destination:
    server: https://kubernetes.default.svc
    namespace: agentgateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
