apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-kagent-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: viper
  source:
    repoURL: oci://ghcr.io/kagent-dev/kagent/helm
    chart: kagent-crds
    targetRevision: 0.10.0-rc2
    helm:
      releaseName: kagent-crds
  destination:
    server: https://kubernetes.default.svc
    namespace: kagent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
