apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-headlamp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: viper
  sources:
    - repoURL: https://kubernetes-sigs.github.io/headlamp/
      chart: headlamp
      targetRevision: 0.44.0
      helm:
        releaseName: headlamp
        valueFiles:
          - $values/platform/headlamp/values.yaml
    - repoURL: https://github.com/sebbycorp/k8s-viper.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
