apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-langfuse
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: viper
  sources:
    - repoURL: https://langfuse.github.io/langfuse-k8s
      chart: langfuse
      targetRevision: 1.5.41
      helm:
        releaseName: langfuse
        valueFiles:
          - $values/platform/langfuse/values.yaml
    - repoURL: https://github.com/sebbycorp/k8s-viper.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: langfuse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
