apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-substrate-rbac
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: viper
  source:
    repoURL: https://github.com/sebbycorp/k8s-viper.git
    targetRevision: main
    path: platform/substrate
  destination:
    server: https://kubernetes.default.svc
    namespace: ate-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
