apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-agentgateway-ai
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: viper
  source:
    repoURL: https://github.com/sebbycorp/k8s-viper.git
    targetRevision: main
    path: platform/agentgateway-ai
  destination:
    server: https://kubernetes.default.svc
    namespace: agentgateway-system
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jqPathExpressions:
        - .spec.data[].remoteRef.conversionStrategy
        - .spec.data[].remoteRef.decodingStrategy
        - .spec.data[].remoteRef.metadataPolicy
        - .spec.target.deletionPolicy
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jqPathExpressions:
        - .spec.parentRefs[].group
        - .spec.parentRefs[].kind
        - .spec.rules[].backendRefs[].weight
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
